// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBvxsLFApZxRqG8x867YusHDXTqESjKIM',
    appId: '1:742957171701:web:a13a1bdf1b2610f3ded6bc',
    messagingSenderId: '742957171701',
    projectId: 'fir-auth-40ede',
    authDomain: 'fir-auth-40ede.firebaseapp.com',
    storageBucket: 'fir-auth-40ede.appspot.com',
    measurementId: 'G-63SQT6E50L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0DiWlu4AEja-UvYjX1_I0lqehZLV3GdU',
    appId: '1:742957171701:android:eacd1009763143f9ded6bc',
    messagingSenderId: '742957171701',
    projectId: 'fir-auth-40ede',
    storageBucket: 'fir-auth-40ede.appspot.com',
  );
}
